# (you can remove the "version" line â€” v2 ignores it and warns)
services:
  app:
    build: ./app
    env_file:
      - ./.env.prod
    environment:
      PYTHONPATH: /srv
    volumes:
      - ./app/data:/srv/app/data          # <-- add this
    depends_on:
      - db
    networks: [internal]
    restart: always


  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sms
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: sms
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [internal]
    restart: always

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddydata:/data
      - caddyconfig:/config
    depends_on: [app]
    networks: [internal, public]
    restart: always

networks:
  internal: {}
  public: {}

volumes:
  pgdata: {}
  caddydata: {}
  caddyconfig: {}

